### ISSUE TITLE
Load detection

### ISSUE THREAD

**Issue by mondalaci** [edwinm/Color-animation-jQuery-plugin#4]
I'd like to be able to reliably detect whether the plugin has loaded so then I can do a CDN to local fallback, like

```
<script src="//cdn.jsdelivr.net/jquery.color-animation/1/mainfile"></script>
<script>jQuery.isColorAnimationPluginLoaded || document.write('<script src="/jquery.color-animation.js"></script>')</script>
```

Any way to do this detection?

Thanks!

**Comment by edwinm** [comment]
László,

I think this should work:

<script src="//cdn.jsdelivr.net/jquery.color-animation/1/mainfile"></script>
<script>(jQuery.Tween && jQuery.Tween.propHooks.color) || document.write('<script src="/jquery.color-animation.js"></script>')</script>

Edwin

**Comment by mondalaci** [comment]
Thanks for the quick reply, Edwin!

I'm a little worried about the `jQuery.Tween && jQuery.Tween.propHooks.color` expression. I expected a simple property check. In which case does `jQuery.Tween` exist?

**Comment by edwinm** [comment]
László,

It is a property check (color). It’s only a bit deep inside jQuery’s data structure.

jQuery.Tween is an interface in jQuery to extend the animate function. Both Tween and propHooks are part of jQuery.

jQuery.Tween.propHooks.color tests whether there is a function that extends .animate(‘color’…).

In theory there could be another extension that extends the color animation, but can’t imagine this happening in practice.

Edwin

**Comment by mondalaci** [comment]
Thanks Edwin, makes sense!

Maybe it'd be worth including this load detection snippet into the documentation. It's quite handy in these situations. Just an idea.

Cheers!
