### ISSUE TITLE
animation in non active tab not works

### ISSUE THREAD

**Issue by Marduke** [edwinm/Color-animation-jQuery-plugin#6]
Hi,

i have followed problem with your plugin. In lastest Firefox (i not tests other) i have page which should indicate live events in out gilab server which can arrive to browser by websocket anytime. To see what is used change background of changed div to blue and than fade back to white with your plugin and everything is good until browser tabs is active. When tab is not active, animation does not starts. Is it problem of Firefox or plugin?

Thanks

**Comment by edwinm** [comment]
I found a bug that sounds very similar: http://stackoverflow.com/questions/11799315/jquery-animation-breaks-when-switching-browser-tabs-in-firefox

Are you using jQuery 3?

**Comment by Marduke** [comment]
Yes, i use jQuery 3.1 . That means it is not a bug, but feature of jquery.
I think that all i need is to detect focus of tab and if it is not active
not run code before animation starts. Maybe i should try use older jquery.

Dne 11. 10. 2016 8:43 PM napsal uživatel "Edwin Martin" <
notifications@github.com>:

**Comment by edwinm** [comment]
Okay. It'll be interesting to hear your findings.

**Comment by Marduke** [comment]
It seems that jQuery 1.12.4 (actual lastest in 1.X) solve the problem.

**Comment by Marduke** [comment]
Hello again,

as i wrote, solution is change jquery to 1.12.4.
OR just simply track tab active state

active = false;

$(window).focus(function() {
  active = true;
});

$(window).blur(function() {
  active = false;  
});

and run animation only if tab active

second opinion is better for me, because lastest version of jquery have better support for our browser and first run more activity in hidden window if no one can see it.

**Comment by Marduke** [comment]
Hello, prevoius comment is not totaly fit my goal.
detection works, but on tab active, so if is visible (for me on second monitor) is doesnt show animation.
visibility fit following function

```
function isTabVisible() {
  if (typeof document.hidden !== "undefined") { // Opera 12.10 and Firefox 18 and later support 
    return !document.hidden;
  } else if (typeof document.msHidden !== "undefined") {
    return !document.msHidden;
  } else if (typeof document.webkitHidden !== "undefined") {
    return !document.webkitHidden;
  }
}
```
